openapi: 3.0.1
info:
  title: db
  description: API Definition of db
  version: 1.0.0
servers:
- url: http://localhost:8290/db
paths:
  /:
    get:
      responses:
        default:
          description: Default response
