openapi: 3.0.1
info:
  title: payloadfactory
  description: API Definition of payloadfactory
  version: 1.0.0
servers:
- url: http://localhost:8290/payloadfactory
paths:
  /:
    get:
      responses:
        default:
          description: Default response
