openapi: 3.0.1
info:
  title: variable
  description: API Definition of variable
  version: 1.0.0
servers:
- url: http://localhost:8290/variable
paths:
  /:
    get:
      responses:
        default:
          description: Default response
